// logo_map.js — shared team logo lookup for umasshockeystats.com
// Loaded by game.html and ncaa_nhl_pipeline.html
// Maps every school name variant used in the site data → PNG filename

const LOGO_MAP = {
  // UMass
  'Massachusetts':           'umass.png',
  'UMass':                   'umass.png',
  'UMass Minutemen':         'umass.png',

  // Hockey East (existing filenames preserved)
  'Boston College':          'BostonCollege.png',
  'Boston University':       'BostonUniversity.png',
  'Connecticut':             'uconn.png',
  'Maine':                   'maine.png',
  'Massachusetts-Lowell':    'UMassLowell.png',
  'UMass Lowell':            'UMassLowell.png',
  'Merrimack':               'merrimack.png',
  'New Hampshire':           'unh.png',
  'Northeastern':            'northeastern.png',
  'Providence':              'providence.png',
  'Vermont':                 'uvm.png',

  // New logos
  'AIC':                     'aic.png',
  'Air Force':               'airforce.png',
  'Alaska':                  'alaska.png',
  'Alaska Anchorage':        'alaskaanchorage.png',
  'Arizona State':           'arizonastate.png',
  'Army':                    'army.png',
  'Bemidji State':           'bemidjistate.png',
  'Bemidji State University':'bemidjistate.png',
  'Bentley':                 'bentley.png',
  'Bowling Green':           'bowlinggreen.png',
  'Brown':                   'brown.png',
  'Clarkson':                'clarkson.png',
  'Colgate':                 'colgate.png',
  'Colorado College':        'coloradocollege.png',
  'Cornell':                 'cornell.png',
  'Dartmouth':               'dartmouth.png',
  'Denver':                  'denver.png',
  'Ferris State':            'FerrisState.png',
  'Harvard':                 'harvard.png',
  'Lake Superior':           'lakesuperior.png',
  'Miami (Ohio)':            'miami.png',
  'Michigan':                'michigan.png',
  'Michigan State':          'michiganstate.png',
  'Michigan Tech':           'michigantech.png',
  'Minnesota':               'minnesota.png',
  'Minnesota State':         'minnesotastate.png',
  'Minnesota-Duluth':        'duluth.png',
  'Nebraska-Omaha':          'omaha.png',
  'North Dakota':            'northdakota.png',
  'Northern Michigan':       'northernmichigan.png',
  'Notre Dame':              'notredame.png',
  'Ohio State':              'ohiostate.png',
  'Omaha':                   'omaha.png',
  'Penn State':              'pennstate.png',
  'Princeton':               'princeton.png',
  'Quinnipiac':              'quinnipiac.png',
  'Robert Morris':           'robertmorris.png',
  'Sacred Heart':            'sacredheart.png',
  'St. Cloud State':         'stcloud.png',
  'St. Lawrence':            'stlawrence.png',
  'Stonehill':               'stonehill.png',
  'Union':                   'union.png',
  'Western Michigan':        'westernmichigan.png',
  'Wisconsin':               'wisconsin.png',
  'Yale':                    'yale.png',
};
